const listTimes = [
  {description: "", value: ''},
  {description: "Programação", value: 'Programação'},
  {description: "Font-End", value: 'Font-End'},
  {description: "Data Science", value: 'Data Science'},
  {description: "Devops", value: 'Devops'},
  {description: "UX e Design", value: 'UX e Design'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Inovação e Gestão", value: 'Inovação e Gestão'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
  {description: "Mobile", value: 'Mobile'},
];
export default listTimes;